from telegram import Update, constants, helpers
from telegram.ext import ContextTypes, CommandHandler
from bot.utils.language import get_msg_string


async def start_handler(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Greets the user with a localized message."""
    text = get_msg_string(update, "common.start")
    safe_text = helpers.escape_markdown(text, version=2)
    await update.message.reply_text(
        safe_text, parse_mode=constants.ParseMode.MARKDOWN_V2
    )


async def user_info_handler(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Displays user metadata using MarkdownV2."""
    user = update.effective_user
    if not user:
        return

    name = helpers.escape_markdown(user.full_name, version=2)
    uid = helpers.escape_markdown(str(user.id), version=2)
    locale = helpers.escape_markdown(user.language_code or "N/A", version=2)

    response = (
        f"*User Profile*\n"
        f"───\n"
        f"*Name:* {name}\n"
        f"*ID:* `{uid}`\n"
        f"*Locale:* `{locale}`\n"
        f"*Premium:* {'Yes' if user.is_premium else 'No'}\n"
        f"───\n"
        f"_Generated by BotTOp Core_"
    )

    await update.message.reply_text(
        response, parse_mode=constants.ParseMode.MARKDOWN_V2
    )


async def echo_handler(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Echoes input. Escapes it to prevent parsing errors."""
    args = update.message.text.split(None, 1)

    if len(args) < 2:
        await update.message.reply_text(
            "*Usage:* `/echo [text]`", parse_mode=constants.ParseMode.MARKDOWN_V2
        )
        return

    safe_payload = helpers.escape_markdown(args[1], version=2)
    await update.message.reply_text(
        safe_payload, parse_mode=constants.ParseMode.MARKDOWN_V2
    )


def __init_module__(application) -> None:
    """Registers handlers for the example module."""
    application.add_handler(CommandHandler(["start", "help"], start_handler))
    application.add_handler(CommandHandler("me", user_info_handler))
    application.add_handler(CommandHandler("echo", echo_handler))
