from telegram import Update, constants, helpers
from telegram.ext import ContextTypes, CommandHandler
from bot.utils.help import get_string_helper, register_module_help


async def start_handler(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Greets the user with a localized message."""
    s = get_string_helper(update)
    await update.message.reply_text(
        helpers.escape_markdown(s("common.start"), version=2),
        parse_mode=constants.ParseMode.MARKDOWN_V2,
    )


async def user_info_handler(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Displays user metadata using MarkdownV2."""
    user = update.effective_user
    if not user:
        return

    e = lambda t: helpers.escape_markdown(str(t), version=2)

    response = (
        f"*User Profile*\n"
        f"───\n"
        f"*Name:* {e(user.full_name)}\n"
        f"*ID:* `{e(user.id)}`\n"
        f"*Locale:* `{e(user.language_code or 'N/A')}`\n"
        f"*Premium:* {'Yes' if user.is_premium else 'No'}\n"
        f"───\n"
        f"_Generated by BotTOp Core_"
    )

    await update.message.reply_text(
        response, parse_mode=constants.ParseMode.MARKDOWN_V2
    )


async def echo_handler(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Echoes input back to the user. Escapes it to prevent parsing errors."""
    args = update.message.text.split(None, 1)

    if len(args) < 2:
        await update.message.reply_text(
            "*Usage:* `/echo [text]`", parse_mode=constants.ParseMode.MARKDOWN_V2
        )
        return

    await update.message.reply_text(
        helpers.escape_markdown(args[1], version=2),
        parse_mode=constants.ParseMode.MARKDOWN_V2,
    )


async def args_handler(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Example of how to handle command arguments. Usage: /args foo bar baz"""
    if not context.args:
        await update.message.reply_text(
            "*Usage:* `/args [arg1] [arg2] \\.\\.\\.`",
            parse_mode=constants.ParseMode.MARKDOWN_V2,
        )
        return

    e = lambda t: helpers.escape_markdown(str(t), version=2)
    args_list = "\n".join(f"• `{e(arg)}`" for arg in context.args)

    await update.message.reply_text(
        f"*You sent {e(len(context.args))} argument\(s\):*\n{args_list}",
        parse_mode=constants.ParseMode.MARKDOWN_V2,
    )


async def localized_handler(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Example of how to use get_string_helper for localized responses."""
    s = get_string_helper(update)
    await update.message.reply_text(
        helpers.escape_markdown(s("common.help"), version=2),
        parse_mode=constants.ParseMode.MARKDOWN_V2,
    )


async def chat_info_handler(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Example of how to access chat metadata."""
    chat = update.effective_chat
    if not chat:
        return

    e = lambda t: helpers.escape_markdown(str(t), version=2)

    await update.message.reply_text(
        f"*Chat Info*\n"
        f"───\n"
        f"*ID:* `{e(chat.id)}`\n"
        f"*Type:* `{e(chat.type)}`\n"
        f"*Title:* {e(chat.title or chat.first_name or 'N/A')}\n",
        parse_mode=constants.ParseMode.MARKDOWN_V2,
    )


# NOTE: This module is an example of how to structure a new module.
# To activate it, implement __init_module__ and move it to bot/modules/.
#
# def __init_module__(application) -> None:
#     application.add_handler(CommandHandler("start", start_handler))
#     application.add_handler(CommandHandler("me", user_info_handler))
#     application.add_handler(CommandHandler("echo", echo_handler))
#     application.add_handler(CommandHandler("args", args_handler))
#     application.add_handler(CommandHandler("localized", localized_handler))
#     application.add_handler(CommandHandler("chat", chat_info_handler))
#     register_module_help("Example", "example.help")  # optional
